pluginManagement {
    val flutterSdkPath =
        run {
            val properties = java.util.Properties()
            file("local.properties").inputStream().use { properties.load(it) }
            val flutterSdkPath = properties.getProperty("flutter.sdk")
            require(flutterSdkPath != null) { "flutter.sdk not set in local.properties" }
            flutterSdkPath
        }

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }

    // Map the Kotlin Android plugin ID to its Maven Central coordinates.
    // This ensures Gradle uses the locally-cached artifact instead of requiring
    // a live connection to the Gradle Plugin Portal for every clean build.
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id.startsWith("org.jetbrains.kotlin")) {
                useModule("org.jetbrains.kotlin:kotlin-gradle-plugin:${requested.version}")
            }
        }
    }
}

plugins {
    id("dev.flutter.flutter-plugin-loader") version "1.0.0"
    id("com.android.application") version "9.1.0" apply false
    // KGP 2.4.0 — generated by Flutter 3.47.5, compatible with AGP 9.1.0.
    // Resolved via the resolutionStrategy above using the locally-cached artifact.
    id("org.jetbrains.kotlin.android") version "2.4.0" apply false
}

include(":app")
